// testReviewAgent.js
// This agent is responsible for reviewing the test results generated by the generator before they are sent to the UI.
// Expert in end-to-end testing, Playwright, and very detail-oriented in code analysis.

const callOllamaLLM = require("../utils/llmOllama");
const { setCurrentProgress } = require("./utils/progressStatus");
const { checkSyntax } = require("./utils/staticSyntaxCheck");

class TestReviewAgent {
  constructor() {
    this.name = "TestReviewAgent";
    this.role = "Expert E2E Test Reviewer";
  }

  /**
   * Evaluate Playwright test script using an LLM expert persona.
   * @param {string} testCode - The generated Playwright test code
   * @returns {Promise<{ approved: boolean, feedback: string[] }>}
   */
  async evaluate(testCode) {
    // Static syntax check before LLM review
    const syntaxError = checkSyntax(testCode);
    if (syntaxError) {
      return {
        approved: false,
        feedback: [
          `Syntax error detected: ${syntaxError}`,
          "Please fix all syntax errors before submitting for review.",
        ],
      };
    }

    const system = `You are an expert in end-to-end testing and Playwright. You are extremely detail-oriented and thorough in reviewing test code. Your job is to review Playwright test scripts and provide detailed, constructive feedback on their quality, coverage, and correctness. If the script is excellent and covers all important cases, respond with '✅ PASS' and a short note. Otherwise, list all issues, missing cases, or improvements needed.`;
    const userPrompt = `PLAYWRIGHT TEST SCRIPT:\n\n${testCode}\n\nPlease review this script for:\n- Test coverage (positive, negative, edge cases)\n- Playwright best practices\n- Code quality and maintainability\n- Any missing or incorrect assertions\n\nGive your feedback as a list. If the script is perfect, just say '✅ PASS'.`;
    const prompt = `${system}\n\n${userPrompt}`;

    setCurrentProgress({
      status: "TestReviewAgent: Evaluating Playwright test script...",
      prompt,
    });
    try {
      const feedbackRaw = await callOllamaLLM({ prompt });
      setCurrentProgress({
        status: "TestReviewAgent: Evaluation finished.",
        prompt,
      });
      const feedback = feedbackRaw.trim().split("\n").filter(Boolean);
      const approved = feedbackRaw.includes("✅ PASS");
      return { approved, feedback };
    } catch (err) {
      setCurrentProgress({
        status: "TestReviewAgent: Error during evaluation.",
        prompt,
      });
      throw err;
    }
  }
}

module.exports = TestReviewAgent;
