// Business logic tests for context: Validasi format email yang benar dan penolakan format email yang salah
// Auto-generated by TestAnalysisAgent
// Context ID: 1
// Acceptance Criteria: Email harus mengikuti format standard (user@domain.com) dan menolak format yang tidak valid

const { test, expect } = require('@playwright/test');

test.describe('Business Logic - Validasi format email yang benar dan penolakan format email yang salah', () => {
    test.beforeEach(async ({ page }) => {
        await page.goto('http://localhost:5500/policy-form.html');
    });

    test('email - business logic validation', async ({ page }) => {
        const field = page.locator('#email');
        
        // Business rule: Email domain validation
        await field.fill('user@company.com');
        await expect(page.locator('.error-message')).toHaveCount(0);
        
    });

    test('integration - complete form submission', async ({ page }) => {
        // Fill all required fields with valid data
        await page.fill('#email', 'test@example.com');
        
        // Submit form
        await page.click('button[type="submit"]');
        
        // Verify submission success
        await expect(page.locator('.success-message')).toBeVisible();
    });

});
